# -*- coding: utf-8 -*-
"""Курсач питон

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Re7OgSwBSurv57EVoM7zCLLFJZoN1Qh
"""

from google.colab import files
import pandas as pd
import matplotlib.pyplot as plt

uploaded_1 = files.upload()
df = pd.read_csv(next(iter(uploaded_1)),sep=',')
display(df)

display(df.info())

"""transaction_id - номер чека

sales_outlet_id - номер магазина

staff_id - номер сотрудника

customer_id - номер клиента (0=гость)

instore_yn - в магазине? (Y/N)

order - номер заказа

line_item_id - номер позиции

product_id - номер товара

quantity - количество

line_item_amount - сумма позиции

unit_price - цена за штуку

promo_item_yn - акционный? (Y/N)

Date - дата и время

# Глава 1
"""

print(df.isnull().sum())

df['Date'] = pd.to_datetime(
    df['transaction_date'] + ' ' + df['transaction_time']
)
df = df.drop(['transaction_date', 'transaction_time'], axis=1)
df['customer_id'] = df['customer_id'].astype('float64')

"""Преобразуем данные в подходящий тип"""

df['customer_id'] = df['customer_id'].astype('int64').astype('str') #в int64 чтобы убрать .0
df['promo_item_yn'] = df['promo_item_yn'].astype('category')
df['sales_outlet_id'] = df['sales_outlet_id'].astype('category')
df['staff_id'] = df['staff_id'].astype('category')
df['product_id'] = df['product_id'].astype('category') #сделаем категорией для дальнейшего анализа товаров бестселлеров
df['instore_yn'] = df['instore_yn'].astype('category')

df['instore_yn'] = df['instore_yn'] == 'Y'
df['promo_item_yn'] = df['promo_item_yn'] == 'Y'

print((df['sales_outlet_id'].unique()))
print(' ')
print((df['staff_id'].unique()))
print(' ')
print((df['product_id'].unique()))

"""выведем уникальные категории в категориальных столбцах"""



#гистограмма
plt.figure(figsize=(5,5))
plt.hist(x=df['quantity'], bins = 'sturges', alpha = 0.8, color='red',
edgecolor = 'black'
, histtype = 'bar', linewidth=0.9, rwidth=0.8)
plt.show()
#ящик с усами
plt.boxplot(x=df['quantity'], vert = False, patch_artist=True,
            boxprops=dict(facecolor='pink'),meanline=True, showmeans = True,
            flierprops = dict(markerfacecolor='red', marker = 's', alpha = 0.75),
            notch = True)
plt.show

"""столбец с quantity не имеет нормального распределения"""



#гистограмма
plt.figure(figsize=(5,5))
plt.hist(x=df['line_item_amount'], bins = 'sturges', alpha = 0.8, color='red',
edgecolor = 'black'
, histtype = 'bar', linewidth=0.9, rwidth=0.8)
plt.show()
#ящик с усами
plt.boxplot(x=df['line_item_amount'], vert = False, patch_artist=True,
            boxprops=dict(facecolor='pink'),meanline=True, showmeans = True,
            flierprops = dict(markerfacecolor='red', marker = 's', alpha = 0.75),
            notch = True)
plt.show()

"""столбец с line_item_amount не имеет нормального распределения"""

#гистограмма
plt.figure(figsize=(5,5))
plt.hist(x=df['unit_price'], bins = 'sturges', alpha = 0.8, color='red',
edgecolor = 'black'
, histtype = 'bar', linewidth=0.9, rwidth=0.8)
plt.show()
#ящик с усами
plt.boxplot(x=df['unit_price'], vert = False, patch_artist=True,
            boxprops=dict(facecolor='pink'),meanline=True, showmeans = True,
            flierprops = dict(markerfacecolor='red', marker = 's', alpha = 0.75),
            notch = True)
plt.show()

"""Столбец unit_price не имеет нормального распределения


"""

#ПОДСЧЕТ ВЫБРОСОВ unit_price
Q1 = df['unit_price'].quantile(0.25)
Q3 = df['unit_price'].quantile(0.75)
IQR = Q3 - Q1
upper_bound = Q3 + 1.5 * IQR

outliers_mask = df['unit_price'] > upper_bound
outliers_count = outliers_mask.sum()
total_rows = len(df)
outliers_percent = (outliers_count / total_rows) * 100
print(outliers_percent)

"""Выбросов мало = можно удалить"""

#ПОДСЧЕТ ВЫБРОСОВ quantity
Q1 = df['quantity'].quantile(0.25)
Q3 = df['quantity'].quantile(0.75)
IQR = Q3 - Q1
upper_bound = Q3 + 1.5 * IQR

outliers_mask = df['quantity'] > upper_bound
outliers_count = outliers_mask.sum()
total_rows = len(df)
outliers_percent = (outliers_count / total_rows) * 100
print(outliers_percent)

"""Выбросов мало = можно удалить"""

#ПОДСЧЕТ ВЫБРОСОВ line_item_amount
Q1 = df['line_item_amount'].quantile(0.25)
Q3 = df['line_item_amount'].quantile(0.75)
IQR = Q3 - Q1
upper_bound = Q3 + 1.5 * IQR

outliers_mask = df['line_item_amount'] > upper_bound
outliers_count = outliers_mask.sum()
total_rows = len(df)
outliers_percent = (outliers_count / total_rows) * 100
print(outliers_percent)

"""Суммарное количество выбросов составляет менее 5%, следовательно их можно удалить"""

df = df[df['quantity'] <= df['quantity'].quantile(0.75) + 1.5*(df['quantity'].quantile(0.75)-df['quantity'].quantile(0.25))]
df = df[df['unit_price'] <= df['unit_price'].quantile(0.75) + 1.5*(df['unit_price'].quantile(0.75)-df['unit_price'].quantile(0.25))]
df = df[df['line_item_amount'] <= df['line_item_amount'].quantile(0.75) + 1.5*(df['line_item_amount'].quantile(0.75)-df['line_item_amount'].quantile(0.25))]

print(df.isna())

"""Пропусков нет. Все 1000 транзакций содержат полную информацию по всем 9 параметрам. Можно сразу переходить к анализу и визуализации без обработки пропусков"""

display(df.duplicated().sum())

"""Дублирующих строк не выявлено, можно переходить к следующему этапу

# Глава 2

Создадим столбец с выручкой
"""

display(df.info())

df['Revenue'] = df['unit_price'] * df['quantity']

"""Построим график по дням и месяцам"""

df1 = df.set_index('Date')['Revenue']
display(df1)

df_w = df1.resample('1D').sum()

plt.figure(figsize=(12, 6))
plt.plot(df_w.index, df_w.values)
plt.show()

"""Наблюдается устойчивая негативная динамика на протяжении всего месяца. Продажи последовательно снижались с уровня около 8000 в начале апреля до 6400 в конце месяца, что указывает на общее падение активности или спроса. Пик активности зафиксирован в начале периода (8000, ориентировочно 1-5 апреля). Наиболее значительное снижение произошло в период с 9 по 13 апреля (падение с 7600 до 7200). Минимальные значения достигнуты в конце месяца (6400, 29 апреля).

Создадим новые категориальные столбцы
"""

df['Hour'] = df['Date'].dt.hour

def get_time_of_day(hour):
    if 5 <= hour < 12:
        return 'Утро'
    elif 12 <= hour < 17:
        return 'День'
    elif 17 <= hour < 22:
        return 'Вечер'
    else:
        return 'Ночь'
df['Time_of_Day'] = df['Hour'].apply(get_time_of_day)

def get_purchase_size(amount):
    if amount < 5:
        return 'Малая'
    elif amount < 15:
        return 'Средняя'
    elif amount < 30:
        return 'Крупная'
    else:
        return 'Очень крупная'

df['Purchase_Size'] = df['line_item_amount'].apply(get_purchase_size)

display(df)
display(df.info())

"""# Глава 3

Проверим гипотезы
H0: Медианный чек у покупок в магазине не различается.
H1: Медианный чек у покупок в магазине различается.
"""

from scipy.stats import kruskal,mannwhitneyu

outlet3 = df[df['sales_outlet_id'] == 3]['Revenue']
outlet5 = df[df['sales_outlet_id'] == 5]['Revenue']
outlet8 = df[df['sales_outlet_id'] == 8]['Revenue']

print(kruskal(outlet3, outlet5, outlet8))

print("Попарные сравнения магазинов:")
print("Магазин 3 и 5:", mannwhitneyu(outlet3, outlet5, alternative='greater'))
print("Магазин 3 и 8:", mannwhitneyu(outlet3, outlet8, alternative='greater'))
print("Магазин 5 и 8:", mannwhitneyu(outlet5, outlet8, alternative='greater'))

"""Статистический анализ с использованием критерия Крускала-Уоллиса выявил наличие статистически значимых различий в медианных чеках между тремя магазинами (p = 0.009, p < 0.05).

Попарные сравнения с использованием U-теста Манна-Уитни показали:

Между магазинами 3 и 5 нет статистически значимых различий (p = 0.280)

Между магазинами 3 и 8 есть статистически значимые различия (p = 0.045)

Между магазинами 5 и 8 есть статистически значимые различия (p = 0.003)

Таким образом, различия в медианных чеках наблюдаются в основном между магазинами 5 и 8, а также между магазинами 3 и 8.
"""

from scipy.stats import kruskal, mannwhitneyu

time_morning = df[df['Time_of_Day'] == 'Утро']['Revenue']
time_afternoon = df[df['Time_of_Day'] == 'День']['Revenue']
time_evening = df[df['Time_of_Day'] == 'Вечер']['Revenue']
time_night = df[df['Time_of_Day'] == 'Ночь']['Revenue']

print(kruskal(time_morning, time_afternoon, time_evening, time_night))
print("Попарные сравнения времени суток:")
print("Утро vs День:", mannwhitneyu(time_morning, time_afternoon, alternative='less'))
print("Утро vs Вечер:", mannwhitneyu(time_morning, time_evening, alternative='less'))
print("Утро vs Ночь:", mannwhitneyu(time_morning, time_night))
print("День vs Вечер:", mannwhitneyu(time_afternoon, time_evening))
print("День vs Ночь:", mannwhitneyu(time_afternoon, time_night))
print("Вечер vs Ночь:", mannwhitneyu(time_evening, time_night))

"""Значимые различия наблюдаются только между утренними покупками и покупками в день/вечер. Утренние чеки статистически значимо отличаются от дневных и вечерних."""

from scipy.stats import kruskal, mannwhitneyu

S = df[df['Purchase_Size'] == 'Малая']['Revenue']
M = df[df['Purchase_Size'] == 'Средняя']['Revenue']
L = df[df['Purchase_Size'] == 'Крупная']['Revenue']
XL = df[df['Purchase_Size'] == 'Очень крупная']['Revenue']

print(kruskal(S, M, L, XL))

print("S vs M:", mannwhitneyu(S, M))
print("S vs L:", mannwhitneyu(S, L))
print("S vs XL:", mannwhitneyu(S, XL))
print("M vs L:", mannwhitneyu(M, L))
print("M vs XL:", mannwhitneyu(M, XL))
print("L vs XL:", mannwhitneyu(L, XL))

print("Количество наблюдений по размеру покупки:")
print("Малая (S):", len(S))
print("Средняя (M):", len(M))
print("Крупная (L):", len(L))
print("Очень крупная (XL):", len(XL))

from scipy.stats import mannwhitneyu

S = df[df['Purchase_Size'] == 'Малая']['Revenue']
M = df[df['Purchase_Size'] == 'Средняя']['Revenue']

print(mannwhitneyu(S, M, alternative='less'))

"""есть статистически значимые различия в медианном чеке между категориями "Малая" и "Средняя"
"""

df['instore_yn'] = 'Online'
df.loc[df['instore_yn'] == True, 'instore_yn'] = 'Offline'

df['promo_item_yn'] = 'Promo'
df.loc[df['promo_item_yn'] == True, 'promo_item_yn'] = 'NP'

display(df)

print(len(df[df['promo_item_yn'] == 'Promo']))
print(len(df[df['promo_item_yn'] == 'NP']))

sales_outlet_category = df.groupby('sales_outlet_id').agg(
    total = ('Revenue', 'sum')
).reset_index().sort_values('total')

plt.figure(figsize=(9, 6))
plt.bar(sales_outlet_category['sales_outlet_id'].astype(str), sales_outlet_category['total'])
plt.title('Доля выручки в зависимости от магазина')
plt.xlabel('Категория')
plt.ylabel('Выручка')
plt.show()

"""Доля выручки неравномерна между магазинами: магазин 8 приносит больше всего выручки, магазин 5 — значительно меньше, а магазин 3 — наименьшую долю."""

time_category = df.groupby('Time_of_Day').agg(
    total = ('Revenue', 'sum')
).reset_index().sort_values('total')

plt.figure(figsize=(9, 6))
plt.bar(time_category['Time_of_Day'], time_category['total'])
plt.title('Доля выручки в зависимости от времени суток')
plt.xlabel('Категория')
plt.ylabel('Выручка')
plt.show()

purchase_category = df.groupby('Purchase_Size').agg(
    total = ('Revenue', 'sum')
).reset_index().sort_values('total')

plt.figure(figsize=(9, 6))
plt.bar(purchase_category['Purchase_Size'], purchase_category['total'])
plt.title('Доля выручки в зависимости от размера покупки')
plt.xlabel('Категория')
plt.ylabel('Выручка')
plt.show()

"""Выручка наиболее высокая в дневное время, снижается вечером и значительно падает ночью и утром. Основная активность покупателей приходится на дневные и вечерние часы.

Проведем РФМ анализ
"""

display(df)
display(df.info())

print(df['Date'].max())

print(df['customer_id'].value_counts().unique())

for_rfm = df[['customer_id','Date','Revenue','transaction_id']]
for_rfm = for_rfm.drop_duplicates()

display(for_rfm)

for_rfm['customer_id'] = for_rfm['customer_id'].astype(int)
for_rfm['transaction_id'] = for_rfm['transaction_id'].astype(int)

display(for_rfm.info())
print(for_rfm['Date'].max())

ф

# Создание отсортированного списка категорий
sorted_categories = rfm_group.sort_values('customer_id', ascending=False)

# Вывод в виде красивой таблицы
print("Рейтинг RFM-сегментов по количеству клиентов:")
print("=" * 50)
print(f"{'Сегмент':<10} {'Кол-во клиентов':<15} {'Доля, %':<10}")
print("-" * 50)

total_clients = sorted_categories['customer_id'].sum()
for _, row in sorted_categories.iterrows():
    print(f"{row['rfm_group']:<10} {row['customer_id']:<15} ")

print("=" * 50)
print(f"Всего клиентов: {total_clients}")

for_rfm['order_recency']=pd.to_datetime('2019-04-29 19:59:28') - pd.to_datetime(for_rfm['Date'].dt.date)
rfm = for_rfm.groupby('customer_id').agg(
    recency = ('order_recency', lambda x: x.min().days),
    frequency = ('transaction_id', 'nunique'),
    monetary_value = ('Revenue', 'sum')
).reset_index()

recency_bins = [-1, 3, 14, 30]
recency_labels = [3, 2, 1]

frequency_bins = [0, 3, 10, float('inf')]
frequency_labels = [1, 2, 3]

monetary_bins = [0, 600, 2500, float('inf')]
monetary_labels = [1, 2, 3]

rfm['r'] = pd.cut(rfm['recency'], bins=recency_bins, labels=recency_labels)
rfm['f'] = pd.cut(rfm['frequency'], bins=frequency_bins, labels=frequency_labels)
rfm['m'] = pd.cut(rfm['monetary_value'], bins=monetary_bins, labels=monetary_labels)

rfm[['r','f','m']] = rfm[['r','f','m']].astype('str')
rfm['rfm_group'] = rfm['r']+rfm['f']+rfm['m']

rfm[['r','f','m']] = rfm[['r','f','m']].astype('int')
rfm['rfm_sum']= rfm[['r','f','m']].sum(axis = 1)

rfm_group = rfm.groupby('rfm_group').agg(
    {'customer_id':'nunique',
     'rfm_sum':'mean'
    }
).reset_index()

display(rfm_group.sort_values(by='rfm_group'))
display(rfm)

# Вариант 1: Из rfm_group (уже готово)
rfm_group_sorted = rfm_group.sort_values('customer_id', ascending=False)
print(rfm_group_sorted[['rfm_group', 'customer_id']])

# Вариант 2: Новая агрегация из rfm
segment_stats = rfm.groupby('rfm_group').agg(
    клиентов=('customer_id', 'nunique'),
    средний_скоринг=('rfm_sum', 'mean')
).sort_values('клиентов', ascending=False)
print(segment_stats)

import plotly.express as px
fig = px.treemap(rfm_group,
                 path = ['rfm_group'],
                 values = 'customer_id',
                 color = 'rfm_sum',
                 color_continuous_scale = 'Sunset',
                 title = 'RFM сегментация пользователей')
fig.show()

"""# ГЛАВА 4"""

model = df[['Date','Revenue']]
display(model.head(2))
display(model.info())
print("кол-во дубликатов",df.duplicated().sum())

model.set_index('Date', inplace = True)
display(model.info())

model.sort_index(inplace=True)

display(model)

model = model['Revenue'].resample('1D').sum()

import matplotlib.pyplot as plt
plt.plot(model.index, model.values)
plt.show()

"""проверим на стационарность с помощью теста дикки фуллера"""

from statsmodels.tsa.stattools import adfuller

p_value = adfuller(model.values)[1]
print(p_value)

"""Ряд стационарен"""

from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

plt.figure(figsize=(12,6))
plt.subplot(121)
plot_acf(model,ax=plt.gca(),lags=20)
plt.title('ACF')

plt.subplot(122)
plot_pacf(model,ax=plt.gca(),lags=len(model) // 2)
plt.title('PACF')

"""по графику акф первый обрыв происходит обрыв после первого лага то параметр MA (скользящее среднее) равен 0
по пакф обрыв (в незначимые значения) - синюю зону, которая явл доверительным
интервалом, произошел после 0 шала поэтому параметр AR (Авторегрессия) = 0
"""

from statsmodels.tsa.arima.model import ARIMA
from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np

train_size = int(len(model)*0.8)
train = model[:train_size]
test=model[train_size:]

model_ = ARIMA(train, order=(0,0,0))
model_fit=model_.fit()

print(model_fit.summary())

"""метрики mse"""

forecast = model_fit.forecast(steps=len(test))
forecast_index = test.index

mse = mean_squared_error(test, forecast) #а ля дисперсия
rmse = np.sqrt(mse) #стандартное откл
mae = mean_absolute_error(test, forecast) #по сути CAO
mape = np.mean(np.abs((test-forecast)/test*100)) # на сколько процентов ошибается модель
print(mse)
print(rmse)
print(mae)
print(mape)

"""7.49 < 10% ошибок следовательно модель хорошо подходит для прогнозирования данных

Проверка остатков на нормальность и автокорелляцию
"""

from statsmodels.stats.diagnostic import acorr_ljungbox
binss = int(np.ceil(np.log2(len(residuals))) + 1)
residuals = model_fit.resid
Ib_test = acorr_ljungbox (residuals, lags=10)
print (Ib_test)
plt. hist(residuals, bins=binss, alpha=0.7)
plt.show()
plot_acf(residuals, lags=20)
plt.show()

"""Тест Льюнга-Бокса: Проведен для 10 лагов. Все p-value превышают уровень значимости 0.05, что свидетельствует об отсутствии статистически значимой автокорреляции в остатках модели.

Ключевые значения:

На первом лаге: p-value = 0.141

На последнем (10-м) лаге: p-value = 0.762

Вывод: Остатки модели являются случайными (белым шумом), автокорреляция отсутствует. Это подтверждается графиком ACF, на котором не обнаружено значимых лагов. Модель адекватно описывает данные.
"""

final_model = ARIMA(model, order=(0,0,0))
final_model_fit = final_model.fit()
future_step = 10
future_forecast = final_model_fit.forecast(steps=future_step)

#создание индексов с датой

last_date = model.index[-1]
future_dates = pd.date_range(start=last_date + pd.Timedelta(days = 1),
                             periods = future_step, freq='1D')

for date, value in zip(future_dates, future_forecast):
  print(f"{date.strftime('%Y-%m-%d')}: {value:.2f}")

plt.figure(figsize=(12,6))

plt.plot(model.index, model.values, label = 'Исходные данные')
plt.plot(future_dates, future_forecast, label = 'Прогнозные данные')
plt.legend()
plt.show()

"""Модель не обнаружила трендовых или сезонных паттернов в данных

Все прогнозы равны среднему историческому значению ряда

Это может указывать на:

Отсутствие выраженных временных зависимостей в данных

Необходимость пересмотра порядка модели (p,d,q)

Возможную стационарность ряда вокруг среднего значения 7176.44

Рекомендация: Рассмотреть другие порядки ARIMA или альтернативные модели для учета возможных паттернов в данных.
"""
